# Generated by Django 4.2.5 on 2023-09-21 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount_unitl',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
