# Generated by Django 4.2.5 on 2023-09-22 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Todo',
        ),
    ]
